### ISSUE TITLE
Deprecation of ratelimiter and Python 3.11 error

### ISSUE THREAD

**Issue by geowa4** [craigerl/aprsd#114]
Per https://github.com/RazerM/ratelimiter/issues/17, ratelimiter is looking for maintainers. The current maintainer recommends using [rush](https://pypi.org/project/rush/) instead. This migration is of particular importance since aprsd does not work with Python 3.11 due to https://github.com/RazerM/ratelimiter/issues/18.

**Comment by hemna** [comment]
thanks for the heads up i will look into it.

**Comment by hemna** [comment]
I have replaced ratelimiter with rush.   Give it a shot from the master branch.
