### ISSUE TITLE
APRSD.conf is not yaml format

### ISSUE THREAD

**Issue by abalashov78** [craigerl/aprsd#171]
Hi!

![image](https://github.com/user-attachments/assets/d7492dd9-e164-4705-b6e0-588dd7c7962a)

aprsd.cfg by default is not yaml format how is needed for aprsd_telegram_bot described here: 
https://github.com/hemna/aprsd-telegram-plugin
![image](https://github.com/user-attachments/assets/3fe87714-6ec4-4683-b3fe-fadd14a90951)

**Comment by hemna** [comment]
The format of the aprsd.conf has changed since the telegram-plugin was written.   I will update the plugin readme to conform to the new format.
