### ISSUE TITLE
Just a questio

### ISSUE THREAD

**Issue by inclanfunk** [craigerl/aprsd#62]
Sorry to push an issue for a simple question. 
I am a webapp designer and I am looking for a software that could send an aprs gps coordinates send from a handy to a web server through a PC with an audio sound board. It is a webapp for firefighters equiped with normal (not digital) handys customed with a micro arduino allowing the gps positioning and sending it througj aprs. Hope it is clear. Many thanks for your help.

**Comment by hemna** [comment]
aprsd now has a webchat command, which brings up an html page to send gps coordinates as a beacon and allows sending aprs messages to any callsign.
