### ISSUE TITLE
RF Only version? 

### ISSUE THREAD

**Issue by W5DMH** [craigerl/aprsd#83]
Very cool project! 
Would love to see a version that parses Direwolf instead of APRS-IS and responds via RF instead of APRS-IS!
73 de Dan W5DMH dan@hurdfarms.com

**Comment by hemna** [comment]
aprsd can connect to direwolf over tcpip or serial

**Comment by W5DMH** [comment]
> 

So the config file should just be pointed to Direwolf? Seems overly simplistic. I tried pointing it at the Xastir server port on the localhost instead of APRS-IS but aprsd expects a successful login so it fails.

**Comment by W5DMH** [comment]
There is an RF version already that can connect to a TNC or to Direwolf. My apologies for not reading further.
